version: 2

.func-job: &func-job
  working_directory: /workspace
  steps:
  - checkout
  - attach_workspace:
      at: /workspace
  - run:
      name: Execute the tests
      command: TBD_INSTALL_RPM=1 test/legacy/run_tests_docker.sh

jobs:
  0-docs:
    docker: [{image: "python:2.7"}]
    working_directory: ~/workspace
    steps:
    - checkout
    - run: git submodule update --init
    - run:
        name: Build documentation with Sphinx
        command: |
          pip install --upgrade -r docs/requirements-doc.txt -e .
          python setup.py --long-description | rst2html.py --verbose --halt=warning > README.html
          make -C docs/ clean html
    - store_artifacts:
        path: README.html
        destination: build/README.html

  0-rpm-centos6:
    docker: [{image: "rpmbuild/centos6"}]
    working_directory: ~/workspace
    steps:
    - run:
        name: Upgrade to descent git version
        command: |
            set -ex
            sudo yum install -y http://opensource.wandisco.com/centos/6/git/x86_64/wandisco-git-release-6-1.noarch.rpm
            sudo yum install -y git
    - checkout
    - run: git submodule update --init
    - run: ./packaging/rpm/build.sh
    - store_artifacts:
        path: ~/workspace/dist/
    - persist_to_workspace:
        root: .
        paths:
        - dist/rpm/noarch/*.rpm

  0-rpm-centos7:
    docker: [{image: "rpmbuild/centos7"}]
    working_directory: ~/workspace
    steps:
    - checkout
    - run: git submodule update --init
    - run: ./packaging/rpm/build.sh
    - store_artifacts:
        path: ~/workspace/dist/
    - persist_to_workspace:
        root: .
        paths:
         - dist/rpm/noarch/*.rpm

  0-unit-py27:
    docker:
      - image: python:2.7
        environment: &unit_env
          TERM: linux
          TERMINFO: /etc/terminfo
    working_directory: /home/ubuntu/temboard-agent
    steps: &unit_steps
      - checkout
      - run: git submodule update --init
      - restore_cache:
          keys:
            - temboard-agent-{{ .Branch }}
            - temboard-agent-master
      - run:
          name: Python lint and tests
          command: |
            set -x
            pip install --upgrade --requirement requirement-ci.txt --editable .
            git diff --check $(git merge-base origin/master $CIRCLE_SHA1)..$CIRCLE_SHA1
            flake8 temboard-agent/
            python -m temboardagent.toolkit.proctitle
            pytest test/unit/
            codecov
      - save_cache:
          key: temboard-agent-{{ .Branch }}
          paths:
            - "~/.cache/pip/"

  0-unit-py36:
    docker:
      - image: python:3.6
        environment: *unit_env
    working_directory: /home/ubuntu/temboard-agent
    steps: *unit_steps

  1-deb-stretch:
    docker: [{image: "dalibo/temboard-agent-sdk:stretch"}]
    working_directory: ~/workspace
    steps:
    - checkout
    - run: git submodule update --init
    - run:
        command: ./packaging/deb/mkdeb.sh
        environment:
          DEBFULLNAME: CircleCI
          DEBEMAIL: none@example.com
    - store_artifacts:
        path: ~/workspace/dist/
    - persist_to_workspace:
        root: .
        paths:
         - dist/*.deb

  1-func-centos7-pg10:
    docker:
    - image: dalibo/temboard-agent-sdk:centos7
      environment:
        TBD_PGBIN: /usr/pgsql-10/bin
    <<: *func-job

  1-func-centos7-pg96:
    docker:
    - image: dalibo/temboard-agent-sdk:centos7
      environment:
        TBD_PGBIN: /usr/pgsql-9.6/bin
    <<: *func-job

  1-func-centos7-pg95:
    docker:
    - image: dalibo/temboard-agent-sdk:centos7
      environment:
        TBD_PGBIN: /usr/pgsql-9.5/bin
    <<: *func-job

  1-func-centos6-pg94:
    docker:
    - image: dalibo/temboard-agent-sdk:centos6
      environment:
        TBD_PGBIN: /usr/pgsql-9.4/bin
    <<: *func-job


workflows:
  version: 2
  pipeline:
    jobs:
    - 0-docs
    - 0-rpm-centos6
    - 0-rpm-centos7
    - 0-unit-py27
    - 0-unit-py36
    - 1-deb-stretch:
        requires: [0-unit-py36]
    - 1-func-centos7-pg10:
        requires: [0-rpm-centos7, 0-unit-py27]
    - 1-func-centos7-pg96:
        requires: [0-rpm-centos7, 0-unit-py27]
    - 1-func-centos7-pg95:
        requires: [0-rpm-centos7, 0-unit-py27]
    - 1-func-centos6-pg94:
        requires: [0-rpm-centos6, 0-unit-py27]
