version: '2'

services:
  centos6: &centos
    image: rpmbuild/centos6
    environment:
    - VERSION
    volumes:
    - ../../:/workspace
    command: /workspace/packaging/rpm/build.sh

  centos7:
    <<: *centos
    image: rpmbuild/centos7
