version: '2'

volumes:
  www:

services:
  reprepro:
    image: bbinet/reprepro
    volumes:
      - www:/data
      - ./reprepro-config:/config-user
      - ./reprepro.sh:/usr/local/bin/docker-command.sh
    command: docker-command.sh
    environment:
      REPREPRO_DEFAULT_NAME: temBoard
      RPP_DISTRIBUTIONS: wheezy;jessie;stretch
      RPP_INCOMINGS: in_oldstable in_stable in_testing
      RPP_ALLOW_in_oldstable: wheezy whatever->wheezy
      RPP_ALLOW_in_stable: jessie whatever->jessie
      RPP_ALLOW_in_testing: stretch whatever->stretch
    container_name: temboard-incoming
    labels:
      com.dnsdock.alias: temboard-incoming.docker

  nginx:
    image: nginx:alpine
    volumes:
      - www:/usr/share/nginx/html:ro
      - ./reprepro-nginx.sh:/usr/local/bin/docker-command.sh
    command: docker-command.sh
    container_name: temboard-repository
    labels:
      com.dnsdock.alias: temboard-repository.docker
